name: PR comment github action tests

on:
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: 
      - created
  pull_request:

jobs:
  get-pr-number:
    runs-on: ubuntu-22.04
    name: Get PR number
    steps:
      - name: Get PR number
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "${{ github.actor }}"
          echo "$PR_NUMBER"
          echo "${{ secrets.DUMMY }}"
          echo 3
          echo $(python -c 'print("hello")')
          echo $(dummy=${{ secrets.DUMMY }} python -c 'import os; foo = os.environ["dummy"][:-2]; print(foo)')          
